<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>

		<!-- AutoMapper -->
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />

		<!-- Database -->
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />

		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />

		<!-- Entity Framework Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime;
				build;
				native;
				contentfiles;
				analyzers;
				buildtransitive
			</IncludeAssets>
		</PackageReference>

		<!-- MediatR -->
		<PackageReference Include="MediatR" Version="14.2.0" />

		<!-- JSON -->
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

		<!-- HTTP -->
		<PackageReference Include="RestSharp" Version="114.0.0" />

		<!-- Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />

		<!-- JWT -->
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />

	</ItemGroup>

</Project>